// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sterlingpro_Ecommerce.Data;

#nullable disable

namespace Sterlingpro_Ecommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sterlingpro_Ecommerce.Data.CartItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics",
                            Description = "Devices and gadgets"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Clothing",
                            Description = "Wearables and fashion"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Books",
                            Description = "Literature and study"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Home & Kitchen",
                            Description = "Appliances and décor"
                        });
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest smartphone",
                            Price = 699m,
                            ProductName = "Smartphone",
                            ProductUrl = "images/smartphone.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High performance laptop",
                            Price = 1099m,
                            ProductName = "Laptop",
                            ProductUrl = "images/laptop.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Wireless sound",
                            Price = 99m,
                            ProductName = "Bluetooth Speaker",
                            ProductUrl = "images/speaker.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Track your health",
                            Price = 199m,
                            ProductName = "Smartwatch",
                            ProductUrl = "images/watch.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Portable computing",
                            Price = 349m,
                            ProductName = "Tablet",
                            ProductUrl = "images/tablet.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Compact audio",
                            Price = 129m,
                            ProductName = "Wireless Earbuds",
                            ProductUrl = "images/earbuds.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Casual wear",
                            Price = 25m,
                            ProductName = "Men's T-shirt",
                            ProductUrl = "images/mens-tshirt.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Summer fashion",
                            Price = 45m,
                            ProductName = "Women's Dress",
                            ProductUrl = "images/womens-dress.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Slim fit jeans",
                            Price = 60m,
                            ProductName = "Jeans",
                            ProductUrl = "images/jeans.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Comfortable shoes",
                            Price = 80m,
                            ProductName = "Sneakers",
                            ProductUrl = "images/sneakers.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Winter wear",
                            Price = 120m,
                            ProductName = "Jacket",
                            ProductUrl = "images/jacket.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Stylish cap",
                            Price = 15m,
                            ProductName = "Cap",
                            ProductUrl = "images/cap.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Learn C#",
                            Price = 39m,
                            ProductName = "C# Programming",
                            ProductUrl = "images/csharp-book.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Web development",
                            Price = 49m,
                            ProductName = "ASP.NET Core",
                            ProductUrl = "images/aspnet-book.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Master EF Core",
                            Price = 35m,
                            ProductName = "EF Core",
                            ProductUrl = "images/efcore-book.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "LINQ explained",
                            Price = 32m,
                            ProductName = "LINQ in Action",
                            ProductUrl = "images/linq-book.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Code quality tips",
                            Price = 45m,
                            ProductName = "Clean Code",
                            ProductUrl = "images/clean-code.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Best practices",
                            Price = 55m,
                            ProductName = "Design Patterns",
                            ProductUrl = "images/design-patterns.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Fast cooking",
                            Price = 199m,
                            ProductName = "Microwave",
                            ProductUrl = "images/microwave.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Smoothies and more",
                            Price = 89m,
                            ProductName = "Blender",
                            ProductUrl = "images/blender.jpg"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Comfortable seating",
                            Price = 499m,
                            ProductName = "Sofa",
                            ProductUrl = "images/sofa.jpg"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "10-piece set",
                            Price = 129m,
                            ProductName = "Cookware Set",
                            ProductUrl = "images/cookware.jpg"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Home cleaning",
                            Price = 159m,
                            ProductName = "Vacuum Cleaner",
                            ProductUrl = "images/vacuum.jpg"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "Modern design",
                            Price = 49m,
                            ProductName = "Wall Clock",
                            ProductUrl = "images/clock.jpg"
                        });
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Data.CartItem", b =>
                {
                    b.HasOne("Sterlingpro_Ecommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.OrderDetail", b =>
                {
                    b.HasOne("Sterlingpro_Ecommerce.Models.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.Product", b =>
                {
                    b.HasOne("Sterlingpro_Ecommerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sterlingpro_Ecommerce.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
